version: '3'

volumes:
  pg_data1:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data1:/var/lib/postgresql/data

  backend:
    image: oleg565/foodgram_backend
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             cp -r /app/collected_static/. /backend_static/static/ &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8001"

  frontend:
    image: oleg565/foodgram_frontend
    restart: always
    depends_on:
      - backend
    env_file: .env
    command: cp -r /app/build/. /staticfiles
    volumes:
      - static:/staticfiles

  gateway:
    image: oleg565/foodgram_gateway
    restart: always
    depends_on:
      - backend
      - frontend
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8001:80
